//__________________________________________________________________________________
//__________________________________________________________________________________
//
//				               PnP DRAGON ARMOR
//__________________________________________________________________________________
//__________________________________________________________________________________

ACTION_FOR_EACH dragonarmor IN BDLEAT05 LEAT19 PLAT18 CHAN20 PLAT20 OHDARMOR cdscale DRAGARM BEGIN

    ACTION_IF FILE_EXISTS_IN_GAME ~%dragonarmor%.itm~ BEGIN

        COPY_EXISTING ~%dragonarmor%.itm~ ~override~
			WRITE_ASCII	0x44 ~GCHAN01~ #8   // Ground icon
            WRITE_ASCII	0x22 ~3A~      #2   // Animation
			WRITE_SHORT 0x26 8              // Min Strength
			WRITE_LONG  0x4c 25             // Weight
			SAY			0x08 @99901    		// Scale Mail
			SAY         0x50 @99902			// Scale Mail Description
		
		LPF DELETE_EFFECT INT_VAR match_opcode = 0 END 	
		LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 1 parameter2 =  2  END
		LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 1 parameter2 =  4  END
		
		BUT_ONLY

    END

END

ACTION_IF GAME_IS ~bgee eet~ BEGIN

COPY_EXISTING ~BDLEAT05.itm~ ~override~
SAY 0x0c @99903                         
SAY 0x54 @99904

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 3 parameter2 = 16  END

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

COPY_EXISTING ~LEAT19.itm~ ~override~
SAY 0x54 @99911

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -8 parameter2 = 16  END

COPY_EXISTING ~PLAT18.itm~ ~override~
SAY 0x54 @99912

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -7 parameter2 = 16  END

COPY_EXISTING ~PLAT20.itm~ ~override~
SAY 0x0c @99905							
SAY 0x54 @99906

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -8 parameter2 = 16  END

COPY_EXISTING ~CHAN20.itm~ ~override~
SAY 0x54 @99913

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -8 parameter2 = 16  END

COPY_EXISTING ~OHDARMOR.itm~ ~override~
SAY 0x54 @99914

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -8 = 16  END

END

ACTION_IF GAME_IS ~iwdee~ BEGIN

COPY_EXISTING ~cdscale.itm~ ~override~
SAY 0x0c @99907							
SAY 0x54 @99908

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = -2 parameter2 = 16  END

COPY_EXISTING ~DRAGARM.itm~ ~override~
SAY 0x0c @99909							
SAY 0x54 @99910

LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 4  parameter2 = 16  END

END