//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						  Icevassal of Auril - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAAuriCM~
    ~RAAuriCM 0 0 0 0 1 1 0 1~
    ~RAAuriCM 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAAuriCM 3 3 13 3 12 3~
	~RAAuriCM 0 0 0 0 0 0~
	~RAAuriCM 3 3 13 3 12 3~
    ~RAAuriCM 3 3 13 3 12 3~
	~RAAuriCM 0 0 0 0 0 1 0 0 0~
	~RAAuriCM 0 0 0 0 0 0~
	~override/RAAuriCM.2da~
	~K_CM_H K_CM_HO K_CM_HE K_CM_D~
	~0x00000000 14~
	~CM0~
	~WA2ROBE * HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * STAF10 HAMM09 *~
	SAY @1701
	SAY @1702
	SAY @1716

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAAuriCM~
		clascolr = ~148 17 105 222 97~
		clsrcreq = ~1 0 1 1 0 0 1~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAAuriCM~
      kit_clab = ~RAAuriCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAAuriCM%	classID = 14 STR_VAR	kitname = ~RAAURI~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMAURI.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMAURI~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMAURI.itm~ SAY NAME1 @1704 SAY NAME2 @1704 SAY DESC @1705
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAAuriCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~AURIS~
WRITE_ASCII 0x058 ~AURIL~

//EoF