//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						  Fastpaw of Baervan - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RABaerCM~
    ~RABaerCM 0 1 1 1 1 0 1 1~
    ~RABaerCM 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RABaerCM 3 3 10 3 9 3~
	~RABaerCM 0 0 0 0 0 0~
	~RABaerCM 3 3 10 3 9 3~
    ~RABaerCM 3 3 10 3 9 3~
	~RABaerCM 0 0 0 1 0 0 1 0 0~
	~RABaerCM 0 0 0 0 0 0~
	~override/RABaerCM.2da~
	~~
	~0x00000000 14~
	~CM0~
	~LEAT19 * HELM16 * RING29 RING31 CLCK27 BOOT04 AMUL27 BRAC10 BELT03 * * * * * * BLUN24 WASLING *~
	SAY @701
	SAY @702
	SAY @709

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RABaerCM~
		clascolr = ~251 43 8 91 9~
		clsrcreq = ~0 0 0 0 0 1 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RABaerCM~
      kit_clab = ~RABaerCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RABaerCM%	classID = 14 STR_VAR	kitname = ~RABAER~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMBAER.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMBAER~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMBAER.itm~ SAY NAME1 @704 SAY NAME2 @704 SAY DESC @705
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RABaerCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~BAERS~
WRITE_ASCII 0x058 ~BAERL~

//EoF