//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						       Deathstalker of Bhaal
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RABhaa~
    ~RABhaa 0 0 0 0 0 0 0 0~
    ~RABhaa 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RABhaa 3 3 12 3 14 3~
	~RABhaa 0 0 0 0 0 0~
	~RABhaa 3 3 12 3 14 3~
    ~RABhaa 3 3 12 3 14 3~
	~RABhaa 0 0 1 0 0 0 0 0 0~
	~RABhaa 1 1 1 1 1 1~
	~DeitiesOfFaerun\Tables\RABhaa.2da~
	~K_C_H K_C_HE K_C_D K_C_HO K_C_E K_C_HL K_C_G~
	~0x04000000 3~
	~Cl0~
	~LEAT21 DAGG14 HELM07 * RING09 RING31 CLCK20 BOOT01 AMUL27 BRAC16 BELT04 * * * * * * SW1H25 HAMM09 *~
	SAY @2401
	SAY @2402
	SAY @2403

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RABhaa~
		clascolr = ~182 47 119 41 182~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

ACTION_INCLUDE ~%MOD_FOLDER%/lib/fnp_compat.tpa~

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 1 rows
	READ_2DA_ENTRY (%rows% - 1) 5 1 mod_clab
 BUT_ONLY

LAF ~DEFINE_FNP_KIT_INFO~
	INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 0
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 0
	u_scimitars 		= 0
	u_katanas 			= 0
	u_bastard_swords 	= 0
	u_2hand_swords 		= 0
	u_halberds 			= 0
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 1

	STR_VAR
    clab_name 	= EVAL ~%mod_clab%~
	class 			= ~cleric~	 
	s_Life 			= ~x~
	s_Death 		= ~major~
	s_Benediction 	= ~x~
	s_Destruction 	= ~major~
	s_Protection 	= ~x~
	s_War 			= ~minor~
	s_Exploration   = ~x~
	s_Knowledge 	= ~minor~	
	s_Deception 	= ~minor~
	s_Thought 		= ~x~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~x~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~major~
	s_Magic 		= ~x~
	s_Perdition     = ~major~
END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
  LAM apply_fnp_spheres
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_fnp_usability.d5~ BEGIN
  LAM apply_fnp_usability
END

COPY "DeitiesOfFaerun\Spl\RAHSBHAA.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@3) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSBHAA.itm" override SAY NAME1 @2408 SAY NAME2 @2408 SAY DESC @2409
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY "DeitiesOfFaerun\Spl\RABHAA1.spl" override SAY NAME1 @2404 SAY UNIDENTIFIED_DESC  @2405                //Bone Dagger


COPY "DeitiesOfFaerun\Spl\RABHAA11.spl" override


COPY_EXISTING ~SPPR708.spl~ ~override/RABHAA2.spl~                                                          //Finger of Death
LPM SPELL_TO_INNATE

COPY "DeitiesOfFaerun\Spl\RABHAA3.spl" override SAY NAME1 @2406 SAY UNIDENTIFIED_DESC  @2407                //Plane Skipping


COPY_EXISTING ~SPPR601.spl~ ~override/RABHAA4.spl~                                                          //Aerial Servant
LPM SPELL_TO_INNATE

COPY "DeitiesOfFaerun\Itm\BoneDagger\RABoneDg.itm" override SAY NAME1 @2304 SAY NAME2 @2304 SAY DESC @2304

COPY "DeitiesOfFaerun\Itm\BoneDagger\RABoneDg.bam" override

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
		89 90 92 93 94 95 99  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@2402)
		  END
		END
		DEFAULT
	END
BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x18 flags1
    PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
	READ_ASCII	0x22 animation (2)
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "4A") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "D1") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "D2") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "D3") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "D4") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C0") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C1") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C2") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C3") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C4") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C5") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
	PATCH_IF ("%animation%" STRING_EQUAL_CASE "C6") BEGIN
	  LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RABhaa~) parameter2 = 9 special = RESOLVE_STR_REF (@2402) END
	END
END
END
BUT_ONLY

ACTION_FOR_EACH file IN ~BHAAS~ ~BHAAL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~BHAABONE~ ~BHAAPLAN~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF