//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					  Deathstalker of Bhaal - Cleric/Thief
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RABhaaCT~
    ~RABhaaCT 0 0 0 0 0 0 0 0~
    ~RABhaaCT 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RABhaaCT 3 3 12 3 14 3~
	~RABhaaCT 0 0 0 0 0 0~
	~RABhaaCT 3 3 12 3 14 3~
    ~RABhaaCT 3 3 12 3 14 3~
	~RABhaaCT 0 0 1 0 0 0 0 0 0~
	~RABhaaCT 0 0 0 0 0 0~
	~override/RABhaaCT.2da~
	~K_CT_H K_CT_HE K_CT_D K_CT_HO K_CT_E K_CT_HL K_CT_G~
	~0x00000000 15~
	~CT0~
	~LEAT21 DAGG14 HELM07 * RING09 RING31 CLCK20 BOOT01 AMUL27 BRAC16 BELT04 * * * * * * SW1H25 HAMM09 *~
	SAY @2401
	SAY @2402
	SAY @2410

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RABhaaCT~
		clascolr = ~182 140 140 62 186~
		clsrcreq = ~1 1 1 1 1 1 1~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RABhaaCT~
      kit_clab = ~RABhaaCT~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RABhaaCT%	classID = 15 STR_VAR	kitname = ~RABHAA~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RATBHAA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACTBHAA~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACTBHAA.itm~ SAY NAME1 @2404 SAY NAME2 @2404 SAY DESC @2405
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RABhaaCT + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~BHAAS~
WRITE_ASCII 0x058 ~BHAAL~

//EoF