//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						       Alaghar of Clangeddin
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAClan~
    ~RAClan 1 1 1 1 3 1 3 1~
    ~RAClan 1 1 1 1 3 1 3 1 1 1 1 3 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAClan 15 3 3 3 9 3~
	~RAClan 0 0 0 0 0 0~
	~RAClan 15 3 3 3 9 3~
    ~RAClan 15 3 3 3 9 3~
	~RAClan 1 1 0 0 0 0 0 0 0~
	~RAClan 1 0 0 0 0 0~
	~DeitiesOfFaerun\Tables\RAClan.2da~
	~K_C_D~
	~0x00000000 3~
	~Cl0~
	~PLAT16 HAMM09 BDHELM09 * RING29 RING31 CLCK05 BOOT04 AMUL27 BRAC10 BELT03 * * * * * * AX1H07 WAFLAIL *~
	SAY @501
	SAY @502
	SAY @503

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAClan~
		clascolr = ~205 5 79 41 105~
		clswpbon = ~1 0 3~
		clsrcreq = ~0 0 0 1 0 0 0~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RACLAN~  clabfile = ~RACLAN~	END

END

//Holy Symbol

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.spl" ~override/RAHSCLAN.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSCLAN~ END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.itm" ~override/RAHSCLAN.itm~ SAY NAME1 @504 SAY NAME2 @504 SAY DESC @505
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAClan + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~CLANS~
WRITE_ASCII 0x058 ~CLANL~

//Spells

COPY "DeitiesOfFaerun\Spl\RAHSCLAN.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSCLAN.itm" override 
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAClan + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

//Command

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_COMMAND[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_COMMAND~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RACLAN1.spl~
LPF	CLONE_EFFECT	INT_VAR	match_opcode = 324 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RACLAN1~	END
LPM ~SPELL_TO_INNATE~

COPY_EXISTING	~%spell_res%.spl~	~override~
LPF	CLONE_EFFECT	INT_VAR	match_opcode = 324 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RACLAN1~	END

END		  

//Spiritual Hammer		  

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_SPIRITUAL_HAMMER[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_SPIRITUAL_HAMMER~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RACLAN2.spl~
LPM ~SPELL_TO_INNATE~

END

//Strength of One

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_STRENGTH_OF_ONE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_STRENGTH_OF_ONE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RACLAN3.spl~
LPM ~SPELL_TO_INNATE~

END

//Defensive Harmony

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_DEFENSIVE_HARMONY[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_DEFENSIVE_HARMONY~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RACLAN4.spl~
LPF	CLONE_EFFECT	INT_VAR	match_opcode = 321 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RACLAN4~	END
LPM ~SPELL_TO_INNATE~

COPY_EXISTING	~%spell_res%.spl~	~override~
LPF	CLONE_EFFECT	INT_VAR	match_opcode = 321 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RACLAN4~	END

END

//Blade Barrier

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_BLADE_BARRIER[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_BLADE_BARRIER~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RACLAN5.spl~
LPM ~SPELL_TO_INNATE~

END

//BAM

ACTION_FOR_EACH file IN ~CLANS~ ~CLANL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF