//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						       Strifeleader of Cyric
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RACyri~
    ~RACyri 1 0 0 0 1 1 0 1~
    ~RACyri 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RACyri 13 3 3 3 13 3~
	~RACyri 0 0 0 0 0 0~
	~RACyri 13 3 3 3 13 3~
    ~RACyri 13 3 3 3 13 3~
	~RACyri 0 0 0 0 0 1 0 0 1~
	~RACyri 0 0 0 1 0 0~
	~DeitiesOfFaerun\Tables\RACyri.2da~
	~K_C_H   K_C_HE   K_C_E   K_C_G   K_C_HO   K_C_HL   K_C_D~
	~0x00000000 3~
	~Cl0~
	~PLAT18 SHLD21 HELM03 * RING22 RING39 CLCK07 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * BLUN14 HAMM09 *~
	SAY @301
	SAY @302
	SAY @303

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RACyri~
		clascolr = ~99 140 60 62 61~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERES.tpa~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RACYRI~  clabfile = ~RACYRI~	END

END

COPY "DeitiesOfFaerun\Spl\RACYRIF.spl" override

COPY "DeitiesOfFaerun\Spl\RAHSCYRI.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSCYRI.itm" override SAY NAME1 @308 SAY NAME2 @308 SAY DESC @309
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RACyri + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY "DeitiesOfFaerun\Spl\RACYRI1.spl" override SAY NAME1 @304 SAY UNIDENTIFIED_DESC @305 //Dark Aura

COPY "DeitiesOfFaerun\Spl\RACYRIE.spl" override                                           //Bonuses for Evil-aligned

COPY "DeitiesOfFaerun\Spl\RACYRIG.spl" override                                           //Penalties for Good-aligned

COPY "DeitiesOfFaerun\Spl\RACYRI2.spl" override SAY NAME1 @306 SAY UNIDENTIFIED_DESC @307 //Instill Madness
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@310) END

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
		89 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RACyri + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@302)
		  END
		END
		DEFAULT
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~CYRIS~ ~CYRIL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~CYRIDAAU~ ~CYRIINMA~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF