ADD_KIT ~RAHUDS~
    ~RAHUDS 1 0 1 1 0 0 0 0~
    ~RAHUDS 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUDS 3 3 16 9 16 3~
	~RAHUDS 0 0 0 0 0 0~
	~RAHUDS 3 3 16 9 16 3~
    ~RAHUDS 3 3 16 9 16 3~
	~RAHUDS 1 0 0 1 0 0 1 0 0~
	~RAHUDS 0 1 0 0 0 0~
	~IHateUndead\Tables\RAHUDS.2da~
	~K_M_H~
	~0x00001000 1~
	~Ma0~
	~CLCK12 * * * RING09 RING39 CLCK02 BOOT01 AMUL21 BRAC03 * * * * * * * * * STAF11~
	SAY @301
	SAY @302
	SAY @303

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAHUDS~		
		clascolr = ~28 30 110 65 21~
		clsrcreq = ~1 0 0 0 0 0 0~
		hpclass = ~HPROG~
END

CREATE spl ~RADSF~

COPY_EXISTING ~RADSF.spl~ override
LPF ADD_ABILITIES	 INT_VAR abil = 1 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 346 target = 2 timing = 9 parameter1 = 2 special = 7 END

COPY ~IHateUndead\Spl\RADS1.spl~ override	SAY NAME1 @304	SAY UNIDENTIFIED_DESC @305
LPF ALTER_SPELL_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@306)   END
LPF ALTER_SPELL_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Regeneration%~ END

COPY ~IHateUndead\Spl\RADS1.bam~ override

//Thanks for helping me out with this one Kjeron, Grammarsalad and Subtledoctor.

COPY_EXISTING_REGEXP ~^.+\.spl$~ override
	READ_LONG  0x64 ab_off
	READ_SHORT 0x68 ab_num
	READ_LONG  0x6a fx_off
	FOR (i = 0; i < ab_num; ++i) BEGIN
		READ_SHORT (ab_off + i * 0x28 + 0x1e) fx_num
		READ_SHORT (ab_off + i * 0x28 + 0x20) fx_idx
		FOR (j = 0; j < fx_num; ++j) BEGIN
			READ_SHORT	(fx_off + (fx_idx + j) * 0x30)	     opcode
			READ_SHORT	(fx_off + (fx_idx + j) * 0x30 + 0x4) parameter1
			PATCH_IF	(opcode = 17 AND parameter1 > 0) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR header = (i + 1) opcode = 321 target = 2 timing = 1 insert_point = 0 STR_VAR resource = EVAL ~RADS1~ END
				SET j = fx_num
			END
		END
	END
BUT_ONLY

COPY_EXISTING_REGEXP ~^.+\.itm$~ override
READ_LONG  0x64 ab_off
READ_SHORT 0x68 ab_num
READ_LONG  0x6a fx_off
	FOR (i = 0; i < ab_num; ++i) BEGIN
		READ_SHORT (ab_off + i * 0x38 + 0x1e) fx_num
		READ_SHORT (ab_off + i * 0x38 + 0x20) fx_idx
		FOR (j = 0; j < fx_num; ++j) BEGIN
			READ_SHORT	(fx_off + (fx_idx + j) * 0x30)	     opcode
			READ_SHORT	(fx_off + (fx_idx + j) * 0x30 + 0x4) parameter1
PATCH_IF	(opcode = 17 AND parameter1 > 0) BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = (i + 1) opcode = 321 target = 2 timing = 1 insert_point = 0 STR_VAR resource = EVAL ~RADS1~ END 
	SET j = fx_num 
END
END
END
BUT_ONLY

/*Multiclass Fighter*/

COPY_EXISTING ~RAHUDS.2da~ ~override\RAHUDSF~

ADD_KIT ~RAHUDSF~
    ~RAHUDSF 1 0 1 1 0 0 0 0~
    ~RAHUDSF 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUDSF 3 3 16 9 16 3~
	~RAHUDSF 0 0 0 0 0 0~
	~RAHUDSF 3 3 16 9 16 3~
    ~RAHUDSF 3 3 16 9 16 3~
	~RAHUDSF 1 0 0 1 0 0 1 0 0~
	~RAHUDSF 0 0 0 0 0 0~
	~override\RAHUDSF.2da~
	~K_FM_H~
	~0x00001000 1~
	~Ma0~
	~CLCK12 * * * RING09 RING39 CLCK02 BOOT01 AMUL21 BRAC03 * * * * * * * * * STAF11~
	SAY @301
	SAY @302
	SAY @307

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAHUDS~		
		clascolr = ~28 30 110 65 21~
		clsrcreq = ~1 0 0 0 0 0 0~
		hpclass = ~HPFT~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAHUDSF~
      kit_clab = ~RAHUDSF~
      base_class = ~M~
	  mc_dir = ~IHateUndead\Lib\Multiclass~
END

//EoF