//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						   Glyphscriber of Deneir - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RADeneCM~
    ~RADeneCM 0 0 0 0 1 1 0 1~
    ~RADeneCM 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RADeneCM 3 3 3 15 15 3~
	~RADeneCM 0 0 0 0 0 0~
	~RADeneCM 3 3 3 15 15 3~
    ~RADeneCM 3 3 3 15 15 3~
	~RADeneCM 0 0 0 1 0 0 0 0 0~
	~RADeneCM 0 0 0 0 0 0~
	~override/RADeneCM.2da~
	~K_CM_H   K_CM_HE   K_CM_E   K_CM_G   K_CM_HL   K_CM_D~
	~0x00000000 14~
	~CM0~
	~WA2ROBE * HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * * BLUN25 *~
	SAY @4301
	SAY @4302
	SAY @4308

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RADeneCM~
		clascolr = ~24 16 105 95 79~
		clsrcreq = ~1 1 1 1 1 1 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RADeneCM~
      kit_clab = ~RADeneCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RADeneCM%	classID = 14 STR_VAR	kitname = ~RADENE~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMDENE.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMDENE~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMDENE.itm~ SAY NAME1 @4304 SAY NAME2 @4304 SAY DESC @4305
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RADeneCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~DENES~
WRITE_ASCII 0x058 ~DENEL~

//EoF