//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						      Pacifist of Eldath
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAElda~
    ~RAElda 1 1 1 1 1 1 1 1~
    ~RAElda 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAElda 3 3 3 3 14 13~
	~RAElda 0 0 0 0 0 0~
	~RAElda 3 3 3 3 14 13~
    ~RAElda 3 3 3 3 14 13~
	~RAElda 0 0 0 1 1 0 0 0 0~
	~RAElda 0 0 0 0 0 1~
	~DeitiesOfFaerun\Tables\RAElda.2da~
	~K_C_H K_C_E K_C_HE K_C_HL~
	~0x00000000 3~
	~Cl0~
	~LEAT19 BLUN10 HELM03 * RING05 RING29 CLCK08 BOOT01 AMUL27 BRAC15 BELT10 * * * * * * * STAF10 BLUN23~
	SAY @4001
	SAY @4002
	SAY @4003

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAElda~
		clascolr = ~3 17 105 98 175~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 0 1 0 0~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAELDA~  clabfile = ~RAELDA~	END

END

//Holy Symbol

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.spl" ~override/RAHSELDA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSELDA~ END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.itm" ~override/RAHSELDA.itm~ SAY NAME1 @4004 SAY NAME2 @4004 SAY DESC @4005
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAElda + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~ELDAS~
WRITE_ASCII 0x058 ~ELDAL~

//Remove Fear

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_REMOVE_FEAR[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_REMOVE_FEAR~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAELDA1.spl~
LPM ~SPELL_TO_INNATE~

END

//Sleep

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SLEEP[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SLEEP~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAELDA2.spl~
LPM ~SPELL_TO_INNATE~

END

//Silence 15' Radius

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_SILENCE_15_FOOT[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_SILENCE_15_FOOT~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAELDA3.spl~
LPM ~SPELL_TO_INNATE~

END

//Sanctuary

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_SANCTUARY[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_SANCTUARY~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAELDA4.spl~
LPM ~SPELL_TO_INNATE~

END

//Multiclass CLAB

COPY_EXISTING ~RAElda.2da~ ~override/RAEldaRC.2da~
SET_2DA_ENTRY 5 25 50 ~AP_RARELDA~
PRETTY_PRINT_2DA

//Restrictions

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 97 98 99 100 101 103 104 105 106 BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAElda + 0x4000)
			  parameter2 = 9
			  timing = 2
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "3A" "D4" "C6" "C2" "C1"  BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAElda~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

//BAM

ACTION_FOR_EACH file IN ~ELDAS~ ~ELDAL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF