//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					  Pacifist of Eldath - Ranger/Cleric
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAEldaRC~
    ~RAEldaRC 1 1 1 1 1 1 1 1~
    ~RAEldaRC 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAEldaRC 3 3 3 3 14 13~
	~RAEldaRC 0 0 0 0 0 0~
	~RAEldaRC 3 3 3 3 14 13~
    ~RAEldaRC 3 3 3 3 14 13~
	~RAEldaRC 0 0 0 1 1 0 0 0 0~
	~RAEldaRC 0 0 0 0 0 0~
	~override/RAEldaRC.2da~
	~K_CR_H K_CR_E K_CR_HE K_CR_HL~
	~0x00000000 18~
	~CR0~
	~LEAT19 BLUN10 HELM03 * RING05 RING29 CLCK08 BOOT01 AMUL27 BRAC15 BELT10 * * * * * * * STAF10 BLUN23~
	SAY @4001
	SAY @4002
	SAY @4006

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAEldaRC~
		clascolr = ~3 17 105 98 175~
		clsrcreq = ~1 1 1 0 1 0 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAEldaRC~
      kit_clab = ~RAEldaRC~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAEldaRC%	classID = 18 STR_VAR	kitname = ~RAELDA~ kitname2 = ~RAELDA~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RARELDA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RARCELDA~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RARCELDA.itm~ SAY NAME1 @4004 SAY NAME2 @4004 SAY DESC @4005
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAEldaRC + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~ELDAS~
WRITE_ASCII 0x058 ~ELDAL~
 
//EoF