//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					           Glitterbright of Garl
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAGarl~
    ~RAGarl 1 1 1 1 1 1 1 1~
    ~RAGarl 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAGarl 3 11 3 11 9 3~
	~RAGarl 0 0 0 0 0 0~
	~RAGarl 3 11 3 11 9 3~
    ~RAGarl 3 11 3 11 9 3~
	~RAGarl 1 0 0 1 0 0 0 0 0~
	~RAGarl 1 0 0 0 0 0~
	~DeitiesOfFaerun/Tables/RAGarl.2da~
	~K_C_G~
	~0x00000000 3~
	~Cl0~
	~PLAT18 SHLD25 HELM04 * RING09 RING28 CLCK27 BOOT04 AMUL27 BRAC10 BELT11 * * * * * * AX1H12 XBOW06 *~
	SAY @5001
	SAY @5002
	SAY @5003

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAGarl~
		clascolr = ~25 48 67 24 25~
		clsrcreq = ~0 0 0 0 0 1 0~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAGARL~  clabfile = ~RAGARL~	END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAHSGARL.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSGARL~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RAHSBARA.itm~ SAY NAME1 @5004 SAY NAME2 @5004 SAY DESC @5005
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAGarl + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~GARLS~
WRITE_ASCII 0x058 ~GARLL~

//Spells

COPY ~DeitiesOfFaerun/Spl/RAGarlF.spl~ override

//Glitterdust
		  
ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_GLITTERDUST[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_GLITTERDUST~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAGARL1.spl~
LPM ~SPELL_TO_INNATE~

END

//Tasha's Uncontrollable Hideous Laughter

COPY ~DeitiesOfFaerun/Spl/RAGARL2.spl~ override SAY NAME1 @5006 SAY UNIDENTIFIED_DESC @5007
LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 1 parameter1 = RESOLVE_STR_REF (@5008) END
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 2; i < 51; ++i)	BEGIN
		INSERT_BYTES (ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE (ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES (fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE (fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68 ab_num
	WRITE_LONG	0x6a fx_off
	FOR (i = 1; i < 51; ++i)	BEGIN
		LPF	ALTER_EFFECT INT_VAR header = (i - 1) match_duration = 6 duration = (6 * i) END
	END

//Mirror Image

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_MIRROR_IMAGE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_MIRROR_IMAGE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAGARL3.spl~
LPM ~SPELL_TO_INNATE~

END

//Improved Invisibility

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_IMPROVED_INVISIBILITY[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_IMPROVED_INVISIBILITY~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAGARL4.spl~
LPM ~SPELL_TO_INNATE~

END

//Multiclass CLAB

COPY_EXISTING ~RAGarl.2da~ ~override/RAGarlFC.2da~
SET_2DA_ENTRY 7 25 50 ~AP_RAFGARL~
PRETTY_PRINT_2DA

//BAM

ACTION_FOR_EACH file IN ~GARLS~ ~GARLL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~GARLTASH~ BEGIN
COPY ~DeitiesOfFaerun/Spl/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF