//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        Doombringer of Hoar
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAHoar~
    ~RAHoar 0 0 0 0 1 1 0 1~
    ~RAHoar 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHoar 3 10 3 3 9 3~
	~RAHoar 0 0 0 0 0 0~
	~RAHoar 3 10 3 3 9 3~
    ~RAHoar 3 10 3 3 9 3~
	~RAHoar 0 1 0 0 0 0 0 0 0~
	~RAHoar 1 0 0 1 0 0~
	~DeitiesOfFaerun\Tables\RAHoar.2da~
	~K_C_H  K_C_HE  K_C_E  K_C_D  K_C_HL  K_C_G  K_C_HO~
	~0x04000000 3~
	~Cl0~
	~PLAT12 SHLD26 HELM07 * RING05 RING28 CLCK05 BOOT05 AMUL27 BRAC10 BELT06 * * * * * * WAFLAIL SW2H15 *~
	SAY @3601
	SAY @3602
	SAY @3603

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAHoar~
		clascolr = ~14 47 63 100 93~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

ACTION_INCLUDE ~%MOD_FOLDER%/lib/fnp_compat.tpa~

 COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 1 rows
	READ_2DA_ENTRY (%rows% - 1) 5 1 mod_clab
 BUT_ONLY

 LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 1
	u_plate_armor 		= 1
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 1
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 1
	u_katanas 			= 1
	u_bastard_swords 	= 1
	u_2hand_swords 		= 1
	u_halberds 			= 1
	u_spears 	 		= 1
	u_darts 			= 1
	u_slings	 		= 1
	u_bows 				= 1
	u_crossbows 		= 1

  STR_VAR
    clab_name 	= EVAL ~%mod_clab%~
	class 			= ~cleric~	 
	s_Life 			= ~x~
	s_Death 		= ~x~
	s_Benediction 	= ~x~
	s_Destruction 	= ~minor~
	s_Protection 	= ~x~
	s_War 			= ~major~
	s_Exploration   = ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~major~
	s_Vigor 		= ~x~
	s_Affliction 	= ~minor~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~major~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
	s_Perdition     = ~major~
END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
  LAM apply_fnp_spheres
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_fnp_usability.d5~ BEGIN
  LAM apply_fnp_usability
END

COPY "DeitiesOfFaerun\Spl\RAHSHoar.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@3) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSHoar.itm" override SAY NAME1 @3609 SAY NAME2 @3609 SAY DESC @3610
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAHoar + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END


COPY_EXISTING ~SPCL321.spl~ ~override/RAHoar1.spl~                                                           //Enrage

COPY_EXISTING ~SPWI115.spl~ ~override/RAHoar2.spl~                                                           //Shocking Grasp
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPWI308.spl~ ~override/RAHoar3.spl~                                                           //Lightning Bolt
LPM SPELL_TO_INNATE

ACTION_IF GAME_IS ~bgee~ BEGIN

COPY_EXISTING ~REVENT.CRE~ ~override/RaHoar4.cre~
WRITE_SHORT 0x270 5
WRITE_LONG  0x08 RESOLVE_STR_REF (@3608)
WRITE_LONG  0x0c RESOLVE_STR_REF (@3608)
WRITE_LONG  0x14 0

END

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

COPY_EXISTING ~REVEN01.CRE~ ~override/RaHoar4.cre~
WRITE_SHORT 0x270 5
WRITE_LONG  0x08 RESOLVE_STR_REF (@3608)
WRITE_LONG  0x0c RESOLVE_STR_REF (@3608)
WRITE_LONG  0x14 0

END

ACTION_IF GAME_IS ~iwdee~ BEGIN

COPY_EXISTING ~REVNANT.CRE~ ~override/RaHoar4.cre~
WRITE_SHORT 0x270 5
WRITE_LONG  0x08 RESOLVE_STR_REF (@3608)
WRITE_LONG  0x0c RESOLVE_STR_REF (@3608)
WRITE_LONG  0x14 0

END

COPY "DeitiesOfFaerun\Spl\RAHoar41.spl"  override

COPY "DeitiesOfFaerun\Spl\RAHoar4.spl"   override SAY NAME1 @3604 SAY UNIDENTIFIED_DESC @3605	             //Hand of Hoar

ADD_PROJECTILE ~DeitiesOfFaerun\Spl\RAHoar5T.PRO~

ADD_PROJECTILE ~DeitiesOfFaerun\Spl\RAHoar5C.PRO~

COPY_EXISTING ~RAHoar5C.PRO~ override
WRITE_SHORT	0x21a %RAHoar5T%

COPY "DeitiesOfFaerun\Spl\RAHoar5.spl"  override SAY NAME1 @3606 SAY UNIDENTIFIED_DESC @3607	             //Thunder Staff
LPF ALTER_SPELL_HEADER INT_VAR projectile = %RAHoar5C% END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL "%RA_Stunned%" END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 2 match_opcode = 139 parameter1 = EVAL "%RA_Deaf%" END

COPY_EXISTING ~SPWI311.spl~ ~override/RAHoar6.spl~                                           	             //Protection From Normal Missile
WRITE_SHORT 0x1C 4                                                    
WRITE_LONG  0x34 1                                                         
WRITE_LONG  0x22 00
LPF ALTER_SPELL_HEADER INT_VAR projectile = 0 target = 5 range = 1 speed = 0 location = 0 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 8   END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 9   END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 50  END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 139 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 141 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 174 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 215 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 156 END
LPF ALTER_EFFECT INT_VAR target = 2 timing = 9 duration = 0 resist_dispel = 0 END

ACTION_FOR_EACH file IN ~HOARS~ ~HOARL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~HOARHAND~ ~HOARTHUN~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF