//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						 Painbearer of Ilmater - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAIlmaCM~
    ~RAIlmaCM 0 0 0 0 1 1 0 1~
    ~RAIlmaCM 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAIlmaCM 3 3 14 3 12 3~
	~RAIlmaCM 0 0 0 0 0 0~
	~RAIlmaCM 3 3 3 3 12 3~
    ~RAIlmaCM 3 3 14 3 12 3~
	~RAIlmaCM 1 0 0 0 0 0 0 0 0~
	~RAIlmaCM 0 0 0 0 0 0~
	~override/RAIlmaCM.2da~
	~K_CM_H   K_CM_HE   K_CM_E   K_CM_G   K_CM_HO   K_CM_HL   K_CM_D~
	~0x00000000 14~
	~CM0~
	~* WAFLAIL HELM04 * RING31 MISC72 OHRCLCK3 BOOT01 AMUL27 BRAC16 BELT09 * * * * * * STAF10 HAMM09 *~
	SAY @1301
	SAY @1302
	SAY @1311

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAIlmaCM~
		clascolr = ~14 28 222 9 14~
		clsrcreq = ~1 1 1 1 1 1 1~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAIlmaCM~
      kit_clab = ~RAIlmaCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAIlmaCM%	classID = 14 STR_VAR	kitname = ~RAILMA~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMILMA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMILMA~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMILMA.itm~ SAY NAME1 @1304 SAY NAME2 @1304 SAY DESC @1305
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAIlmaCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~ILMAS~
WRITE_ASCII 0x058 ~ILMAL~

//EoF