//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        Doomscribe of Jergal
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAJerg~
    ~RAJerg 0 0 0 0 0 0 0 0~
    ~RAJerg 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAJerg 3 3 3 11 9 3~
	~RAJerg 0 0 0 0 0 0~
	~RAJerg 3 3 3 11 9 3~
    ~RAJerg 3 3 3 11 9 3~
	~RAJerg 0 1 1 0 0 0 0 0 0~
	~RAJerg 0 0 1 0 0 0~
	~DeitiesOfFaerun\Tables\RAJerg.2da~
	~K_C_H~
	~0x00000000 3~
	~Cl0~
	~PLAT05 SHLD25 HELM17 * RING09 RING39 CLCK05 BOOT04 AMUL27 BRAC10 BELT04 * * * * * * BLUN25 HAMM09 *~
	SAY @2801
	SAY @2802
	SAY @2803

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAJerg~
		clascolr = ~6 110 186 185 187~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 0 0 0 0 0 0~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAJERG~  clabfile = ~RAJERG~	END

END

COPY "DeitiesOfFaerun\Spl\RAJergF.spl" override

COPY "DeitiesOfFaerun\Spl\RAHSJERG.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSJERG.itm" override SAY NAME1 @2806 SAY NAME2 @2806 SAY DESC @2807
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAJerg + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY_EXISTING ~SPWI221.spl~ ~override/RAJERG1.spl~    //Ray of Enfeeblement
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPWI313.spl~ ~override/RAJERG2.spl~    //Skull Trap
LPM SPELL_TO_INNATE

//Undead Ward

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_UNDEAD_WARD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_UNDEAD_WARD~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAJERG3.spl~
SAY NAME1 @9999100 SAY UNIDENTIFIED_DESC @9999101
LPM ~SPELL_TO_INNATE~

END ELSE BEGIN

ADD_PROJECTILE ~DeitiesofFaerun/Lib/Spheres/Import/UndeadWard/UWARD.PRO~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/UndeadWard/SPPR521.spl~  ~override/RAJERG3.spl~
SAY NAME1 @9999100 SAY NAME2 @9999100 SAY UNIDENTIFIED_DESC @9999101 SAY DESC @9999101
LPF ALTER_SPELL_HEADER INT_VAR projectile = %UWARD% END
LPM ~SPELL_TO_INNATE~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/UndeadWard/SPPR521B.BAM~	~override~
COPY ~DeitiesofFaerun/Lib/Spheres/Import/UndeadWard/SPPR521C.BAM~	~override~

END

COPY_EXISTING ~SPPR413.spl~ ~override/RAJERG4.spl~    //Negative Plane Protection
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPWI501.spl~ ~override/RAJERG5.spl~    //Animate Dead
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPWI914.spl~ ~override/RAJERG6.spl~    //Energy Drain
LPM SPELL_TO_INNATE
		  
		  
COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
	89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAJerg + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@2802)
		  END
		END
		DEFAULT
	END
BUT_ONLY	
	
ACTION_FOR_EACH file IN ~JERGS~ ~JERGL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF