//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        Doomguide of Kelemvor
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAKele~
    ~RAKele 0 0 0 0 0 0 0 0~
    ~RAKele 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAKele 3 3 12 3 14 3~
	~RAKele 0 0 0 0 0 0~
	~RAKele 3 3 12 3 14 3~
    ~RAKele 3 3 12 3 14 3~
	~RAKele 0 1 0 0 0 0 0 0 0~
	~RAKele 1 0 0 0 0 0~
	~DeitiesOfFaerun\Tables\RAKele.2da~
	~K_C_H K_C_HE K_C_D K_C_HO K_C_E K_C_HL K_C_G~
	~0x04000000 3~
	~Cl0~
	~CHAN18 BLUN14 HELM04 * RING09 RING31 CLCK20 BOOT01 AMUL27 BRAC10 BELT04 * * * * * * XBOW06 HAMM09 *~
	SAY @2601
	SAY @2602
	SAY @2603

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAKele~
		clascolr = ~6 43 137 95 30~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERES.tpa~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAKELE~  clabfile = ~RAKELE~	END

END

COPY "DeitiesOfFaerun\Spl\RAKELEF.spl" override

COPY "DeitiesOfFaerun\Spl\RAHSKELE.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@3) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSKELE.itm" override SAY NAME1 @2607 SAY NAME2 @2607 SAY DESC @2608
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAKele + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY "DeitiesOfFaerun\Spl\RAKELE1.spl" override SAY NAME1 @2605 SAY UNIDENTIFIED_DESC @2606          //Chilling Scythe

COPY "DeitiesOfFaerun\Itm\ChillingScythe\KELESCYT.itm" override SAY NAME1 @2605 SAY NAME2 @2605      //Chilling Scythe (Itm)

COPY "DeitiesOfFaerun\Itm\ChillingScythe\KELESBLD.spl" override                                      //Chilling Scythe (Spl)

COPY "DeitiesOfFaerun\Itm\ChillingScythe\KELESBLD.bam" override                                      //Chilling Scythe (Bam)
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun\Itm\ChillingScythe\MOS%original_base_index%.pvrz~
    END
  END

COPY_EXISTING ~SPPR413.spl~ ~override/RAKELE2.spl~
WRITE_SHORT 0x1C 4                                                    
WRITE_LONG  0x34 1                                                         
WRITE_LONG  0x22 00
LPF ALTER_SPELL_HEADER INT_VAR projectile = 0 target = 5 range = 1 speed = 0 location = 0 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 9   END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 50  END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 139 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 141 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 174 END
LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 215 END
LPF ALTER_EFFECT INT_VAR target = 2 timing = 9 duration = 0 resist_dispel = 0 END
		  
COPY "DeitiesOfFaerun\Spl\RAKELE3.spl" override  SAY NAME1 @2505 SAY  UNIDENTIFIED_DESC @2607 //Summon Minor Death

COPY "DeitiesOfFaerun\Spl\RAKELE3.eff" override

COPY "DeitiesOfFaerun\Cre\MinorDeath\RAMinDSu.cre" override SAY NAME1 @2504 SAY NAME2 @2504   //Minor Death - creature

COPY "DeitiesOfFaerun\Cre\MinorDeath\RAMinDSu.itm" override                                   //Minor Death - weapon/immunities 
    LPF ALTER_EFFECT INT_VAR match_parameter1 = 1  match_opcode = 267 parameter1 = EVAL "%RA_Poison%" END
    LPF ALTER_EFFECT INT_VAR match_parameter1 = 2  match_opcode = 267 parameter1 = EVAL "%RA_Poisoned%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 3  match_opcode = 267 parameter1 = EVAL "%RA_Diseased%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 4  match_opcode = 267 parameter1 = EVAL "%RA_FoulDisease%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 5  match_opcode = 267 parameter1 = EVAL "%RA_Bleeding%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 6  match_opcode = 267 parameter1 = EVAL "%RA_Berserk%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 7  match_opcode = 267 parameter1 = EVAL "%RA_Feebleminded%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 8  match_opcode = 267 parameter1 = EVAL "%RA_Sleep%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 9  match_opcode = 267 parameter1 = EVAL "%RA_Stun%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 10 match_opcode = 267 parameter1 = EVAL "%RA_Stunned%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 11 match_opcode = 267 parameter1 = EVAL "%RA_RigidThink%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 12 match_opcode = 267 parameter1 = EVAL "%RA_Panic%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 13 match_opcode = 267 parameter1 = EVAL "%RA_MoralFail%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 14 match_opcode = 267 parameter1 = EVAL "%RA_Drain1%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 15 match_opcode = 267 parameter1 = EVAL "%RA_Drain2%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 16 match_opcode = 267 parameter1 = EVAL "%RA_Drain3%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 17 match_opcode = 267 parameter1 = EVAL "%RA_Drain4%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 18 match_opcode = 267 parameter1 = EVAL "%RA_Drain5%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 19 match_opcode = 267 parameter1 = EVAL "%RA_Charmed%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 20 match_opcode = 267 parameter1 = EVAL "%RA_DireCharmed%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 21 match_opcode = 267 parameter1 = EVAL "%RA_Held%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 22 match_opcode = 267 parameter1 = EVAL "%RA_Paralyzed%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 23 match_opcode = 267 parameter1 = EVAL "%RA_Dominated%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 24 match_opcode = 267 parameter1 = EVAL "%RA_Confused%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 25 match_opcode = 267 parameter1 = EVAL "%RA_Blinded%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 26 match_opcode = 267 parameter1 = EVAL "%RA_Hopeless%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 27 match_opcode = 267 parameter1 = EVAL "%RA_AbDrain%" END
	LPF ALTER_EFFECT INT_VAR match_parameter1 = 28 match_opcode = 267 parameter1 = EVAL "%RA_IntDrain%" END
	
COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 92 93 94 95 99  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAKele + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@2602)
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "D1" "D2" "D3" "D4" "C0" "C1" "C2" "C3" "C4" "C5" "C6" BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAKele~) parameter2 = 9 special = RESOLVE_STR_REF (@2602) END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY


ACTION_FOR_EACH file IN ~KELES~ ~KELEL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~KELEDEAT~ ~KELESCYT~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF