// Use kits' colors for armors, helmets and shields.

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_ASCII 0x22 animation (2)
  READ_LONG 0x18 flags
  PATCH_IF (((flags & BIT6) = 0) AND ((("%animation%" STRING_EQUAL_CASE "4A")) OR (("%animation%" STRING_EQUAL_CASE "3A")) OR (("%animation%" STRING_EQUAL_CASE "2A")))) BEGIN
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 7  END                                   
  END
  BUT_ONLY


//EoF