//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					      Mistcaller of Leira - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RALeirCM~
    ~RALeirCM 0 0 0 0 1 1 0 1~
    ~RALeirCM 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RALeirCM 3 11 3 12 14 3~
	~RALeirCM 0 0 0 0 0 0~
	~RALeirCM 3 11 3 12 14 3~
    ~RALeirCM 3 11 3 12 14 3~
	~RALeirCM 0 0 0 0 0 0 0 1 1~
	~RALeirCM 0 0 0 0 0 0~
	~override/RALeirCM.2da~
	~K_CM_H  K_CM_HE  K_CM_G~
	~0x00000400 14~
	~CM0~
	~* * * * * * * * * * * * * * * * * * * *~
	SAY @3301
	SAY @3302
	SAY @3307

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RALeirCM~
		clascolr = ~100 91 114 92 100~
		clsrcreq = ~1 0 1 0 0 1 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RALeirCM~
      kit_clab = ~RALeirCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RALeirCM%	classID = 14 STR_VAR	kitname = ~RALEIR~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMLEIR.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMLEIR~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMLEIR.itm~ SAY NAME1 @3304 SAY NAME2 @3304 SAY DESC @3305
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RALeirCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~LEIRS~
WRITE_ASCII 0x058 ~LEIRL~

//EoF