//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						      Mistcaller of Leira
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RALeir~
    ~RALeir 0 0 0 0 1 1 0 1~
    ~RALeir 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RALeir 3 11 3 12 14 3~
	~RALeir 0 0 0 0 0 0~
	~RALeir 3 11 3 12 14 3~
    ~RALeir 3 11 3 12 14 3~
	~RALeir 0 0 0 0 0 0 0 1 1~
	~RALeir 0 0 1 1 0 0~
	~DeitiesOfFaerun\Tables\RALeir.2da~
	~K_C_H  K_C_HE  K_C_G~
	~0x00000000 3~
	~Cl0~
	~* * * * * * * * * * * * * * * * * * * *~
	SAY @3301
	SAY @3302
	SAY @3303

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RALeir~
		clascolr = ~100 91 114 92 100~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 0 1 0 0 1 0~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RALEIR~  clabfile = ~RALEIR~	END

END

COPY "DeitiesOfFaerun\Spl\RALeirF.spl" override

COPY "DeitiesOfFaerun\Spl\RAHSLEIR.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSLEIR.itm" override SAY NAME1 @3304 SAY NAME2 @3304 SAY DESC @3305
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RALeir + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

//Mirror Image

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_MIRROR_IMAGE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_MIRROR_IMAGE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR1.spl~
LPM ~SPELL_TO_INNATE~

END

//Blur

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_BLUR[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_BLUR~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR2.spl~
LPM ~SPELL_TO_INNATE~

END

//Shadow Monsters

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SHADOW_MONSTERS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SHADOW_MONSTERS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR3.spl~
LPM ~SPELL_TO_INNATE~

END

//Demi-Shadow Monsters

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_DEMI_SHADOW_MONSTERS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_DEMI_SHADOW_MONSTERS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR4.spl~
LPM ~SPELL_TO_INNATE~

END

//Mislead

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_MISLEAD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_MISLEAD~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR5.spl~
LPM ~SPELL_TO_INNATE~

END

//Project Image

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_PROJECT_IMAGE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_PROJECT_IMAGE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RALEIR6.spl~
LPM ~SPELL_TO_INNATE~

END

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RALeir + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@3302)
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "3A" "2A" BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RALeir~) parameter2 = 9 special = RESOLVE_STR_REF (@3302) END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~LEIRS~ ~LEIRL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF