//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        Silentwalker of Mask
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAMask~
    ~RAMask 0 0 0 0 1 1 0 0~
    ~RAMask 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAMask 3 14 3 3 14 3~
	~RAMask 0 0 0 0 0 0~
	~RAMask 14 3 3 3 12 3~
    ~RAMask 14 3 3 3 12 3~
	~RAMask 0 0 0 0 0 1 0 0 0~
	~RAMask 0 0 0 1 0 0~
	~DeitiesOfFaerun\Tables\RAMask.2da~
	~K_C_H   K_C_HE   K_C_E   K_C_G   K_C_HO   K_C_HL   K_C_D~
	~0x00000000 3~
	~Cl0~
	~LEAT17 * HELM04 * RING05 RING39 CLCK03 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * DAGG11 WAFLAIL *~
	SAY @1601
	SAY @1602
	SAY @1603

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAMask~
		clascolr = ~206 107 138 107 104~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAMASK~  clabfile = ~RAMASK~	END

END

//Holy Symbol

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.spl" ~override/RAHSMASK.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSMASK~ END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHS.itm" ~override/RAHSMASK.itm~ SAY NAME1 @1604 SAY NAME2 @1604 SAY DESC @1605
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAMask + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~MASKS~
WRITE_ASCII 0x058 ~MASKL~

//Spells

//Darkness

ACTION_IF !FILE_EXISTS_IN_GAME ~RADARK.PRO~ BEGIN
	ADD_PROJECTILE ~DeitiesOfFaerun\Spl\RADARK.PRO~
	COPY "DeitiesOfFaerun\Spl\UB!Dark.bam" override
END ELSE BEGIN
	OUTER_SPRINT	file ~RADARK~
	COPY_EXISTING ~PROJECTL.IDS~	override
		REPLACE_EVALUATE ~[%WNL%^]\(0x[0-9A-F]+\|[0-9]+\)[ %TAB%]+%file%[ %TAB%%WNL%$]~	BEGIN	SET	EVAL ~%file%~ = (~%MATCH1%~ -1)	END	~%MATCH0%~
	BUT_ONLY
END
		  
COPY "DeitiesOfFaerun\Spl\RAMASK1.spl" override  SAY NAME1 @406 SAY  UNIDENTIFIED_DESC @407     
LPF ALTER_SPELL_HEADER INT_VAR projectile = %RADARK% END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL "%RA_Blinded%" END

//Shadowcloak

COPY "DeitiesOfFaerun\Spl\RAMASK2.spl" override  SAY NAME1 @1606 SAY  UNIDENTIFIED_DESC @1607   
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 3; i < 51; ++i)	BEGIN
		INSERT_BYTES	(ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE	(ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES	(fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE	(fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68	ab_num
	WRITE_LONG	0x6a	fx_off
	FOR (i = 2; i < 51; ++i)	BEGIN
		LPF	ALTER_EFFECT	INT_VAR	header = (i - 2) match_duration = 6 duration = (6 * i) END
	END

//Shadow Door

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SHADOW_DOOR[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SHADOW_DOOR~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK3.spl~
LPM ~SPELL_TO_INNATE~

END

//Shadow Monsters

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SHADOW_MONSTERS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SHADOW_MONSTERS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK4.spl~
LPM ~SPELL_TO_INNATE~

END ELSE BEGIN

LAF cd_new_summon_table STR_VAR descript = "SHADOW_MONSTERS" 2da_file = SMONSTE RET SMONSTE = table END
ADD_SPELL ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SPWI426.spl~ 2 4 WIZARD_SHADOW_MONSTERS
SAY NAME1 @999964 SAY NAME2 @999964 SAY UNIDENTIFIED_DESC @999965 SAY DESC @999965
TEXT_SPRINT	spell_res	~%DEST_RES%~	TO_UPPER	spell_res
WRITE_ASCIIE	0x3a ~%spell_res%C~	#8
LPF	ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_res%B~	END
LPF	ALTER_EFFECT	   STR_VAR silent = 1  match_resource = EVAL ~%SOURCE_RES%~	  resource = EVAL ~%spell_res%~	    END
LPF ALTER_EFFECT	   INT_VAR match_opcode = 331 parameter2 = SMONSTE END

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SPWI426B.BAM~	~override\%spell_res%B.BAM~
COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SPWI426C.BAM~	~override\%spell_res%C.BAM~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SMONSTE.2DA~	~override~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1GOB1.CRE~	~override~
SAY NAME1 @999966 SAY NAME2 @999966

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1GOB2.CRE~	~override~
SAY NAME1 @999966 SAY NAME2 @999966

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1GOB3.CRE~	~override~
SAY NAME1 @999966 SAY NAME2 @999966

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1LIZ3.CRE~	~override~
SAY NAME1 @999967 SAY NAME2 @999967

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1LIZ4.CRE~	~override~
SAY NAME1 @999967 SAY NAME2 @999967

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1TRL6.CRE~	~override~
SAY NAME1 @999968 SAY NAME2 @999968

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1TRL7.CRE~	~override~
SAY NAME1 @999968 SAY NAME2 @999968

COPY ~DeitiesofFaerun/Lib/Spheres/Import/ShadowMonsters/SS1TRL8.CRE~	~override~
SAY NAME1 @999968 SAY NAME2 @999968

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK4.spl~
LPM ~SPELL_TO_INNATE~

END

//Demi-Shadow Monsters

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_DEMI_SHADOW_MONSTERS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_DEMI_SHADOW_MONSTERS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK5.spl~
LPM ~SPELL_TO_INNATE~

END ELSE BEGIN

LAF cd_new_summon_table STR_VAR descript = "DEMI_SHADOW_MONSTERS" 2da_file = DSMONST RET DSMONST = table END
ADD_SPELL ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SPWI525.spl~ 2 5 WIZARD_DEMI_SHADOW_MONSTERS
SAY NAME1 @999969 SAY NAME2 @999969 SAY UNIDENTIFIED_DESC @999970 SAY DESC @999970
TEXT_SPRINT	spell_res	~%DEST_RES%~	TO_UPPER	spell_res
WRITE_ASCIIE	0x3a ~%spell_res%C~	#8
LPF	ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_res%B~	END
LPF	ALTER_EFFECT	   STR_VAR silent = 1 match_resource = EVAL ~%SOURCE_RES%~	  resource = EVAL ~%spell_res%~	    END
LPF ALTER_EFFECT	   INT_VAR match_opcode = 331 parameter2 = DSMONST END

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SPWI525B.BAM~	~override\%spell_res%B.BAM~
COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SPWI525C.BAM~	~override\%spell_res%C.BAM~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/DSMONST.2DA~	    ~override~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2GOB1.CRE~	    ~override~
SAY NAME1 @999971 SAY NAME2 @999971

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2GOB2.CRE~		~override~
SAY NAME1 @999971 SAY NAME2 @999971

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2GOB3.CRE~		~override~
SAY NAME1 @999971 SAY NAME2 @999971

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2LIZ5.CRE~		~override~
SAY NAME1 @999972 SAY NAME2 @999972

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2LIZ6.CRE~		~override~
SAY NAME1 @999972 SAY NAME2 @999972

COPY ~DeitiesofFaerun/Lib/Spheres/Import/DemiShadowMonster/SS2LIZ7.CRE~		~override~
SAY NAME1 @999972 SAY NAME2 @999972

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK5.spl~
LPM ~SPELL_TO_INNATE~

END

//Summon Shadow

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SUMMON_SHADOW[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SUMMON_SHADOW~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK6.spl~
LPM ~SPELL_TO_INNATE~

END ELSE BEGIN

LAF cd_new_summon_table STR_VAR descript = "SUMMON_SHADOW" 2da_file = SSHADOW RET SSHADOW = table END
ADD_SPELL ~DeitiesofFaerun/Lib/Spheres/Import/SummonShadow/SPWI526.spl~ 2 5 WIZARD_SUMMON_SHADOW
SAY NAME1 @999976 SAY NAME2 @999976 SAY UNIDENTIFIED_DESC @999977 SAY DESC @999977
TEXT_SPRINT	spell_res	~%DEST_RES%~	TO_UPPER	spell_res
WRITE_ASCIIE	0x3a ~%spell_res%C~	#8
LPF	ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_res%B~	END
LPF	ALTER_EFFECT	   STR_VAR silent = 1 match_resource = EVAL ~%SOURCE_RES%~	  resource = EVAL ~%spell_res%~	    END
LPF ALTER_EFFECT	   INT_VAR match_opcode = 331 parameter2 = SSHADOW END

COPY ~DeitiesofFaerun/Lib/Spheres/Import/SummonShadow/SPWI526B.BAM~	~override\%spell_res%B.BAM~
COPY ~DeitiesofFaerun/Lib/Spheres/Import/SummonShadow/SPWI526C.BAM~	~override\%spell_res%C.BAM~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/SummonShadow/SSHADOW.2DA~	~override~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/SummonShadow/SUMSHAD.CRE~	~override~
SAY NAME1 @999978 SAY NAME2 @999978

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK6.spl~
LPM ~SPELL_TO_INNATE~

END

//Shades

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SHADES[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SHADES~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK7.spl~
LPM ~SPELL_TO_INNATE~

END ELSE BEGIN

LAF cd_new_summon_table STR_VAR descript = "SHADES" 2da_file = SHADES RET SHADES = table END
ADD_SPELL ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SPWI629.spl~ 2 6 WIZARD_SHADES
SAY NAME1 @999973 SAY NAME2 @999973 SAY UNIDENTIFIED_DESC @999974 SAY DESC @999974
TEXT_SPRINT	spell_res	~%DEST_RES%~	TO_UPPER	spell_res
WRITE_ASCIIE	0x3a ~%spell_res%C~	#8
LPF	ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_res%B~	END
LPF	ALTER_EFFECT	   STR_VAR silent = 1 match_resource = EVAL ~%SOURCE_RES%~	  resource = EVAL ~%spell_res%~	    END
LPF ALTER_EFFECT	   INT_VAR match_opcode = 331 parameter2 = SHADES END

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SPWI629B.BAM~	~override\%spell_res%B.BAM~
COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SPWI629C.BAM~	~override\%spell_res%C.BAM~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SHADES.2DA~	    ~override~

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SS3TRL7.CRE~	~override~
SAY NAME1 @999968 SAY NAME2 @999968

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SS3TRL8.CRE~	~override~
SAY NAME1 @999968 SAY NAME2 @999968

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SS3UMB8.CRE~	~override~
SAY NAME1 @999975 SAY NAME2 @999975

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/SS3UMB9.CRE~	~override~
SAY NAME1 @999975 SAY NAME2 @999975

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/REG1HP2.ITM~	~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35600 parameter1 = EVAL "%RA_UndeadD%" END
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35591 parameter1 = EVAL "%RA_Death%"   END
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35592 parameter1 = EVAL "%RA_Vorpal%"  END

COPY ~DeitiesofFaerun/Lib/Spheres/Import/Shades/CDIWDTR1.SPL~	~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 35593 parameter1 = EVAL "%RA_Diseased%" END
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 39752 parameter1 = EVAL "%RA_FoulDisease%" END
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 36317 parameter1 = EVAL "%RA_Poison%" END
LPF ALTER_EFFECT INT_VAR match_opcode = 267 match_parameter1 = 37607 parameter1 = EVAL "%RA_Poisoned%" END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK7.spl~
LPM ~SPELL_TO_INNATE~

END

//Invisible Stalker

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_INVISIBLE_STALKER[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_INVISIBLE_STALKER~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAMASK8.spl~
LPM ~SPELL_TO_INNATE~

END

COPY_EXISTING ~smtables.2da~ ~override~
PRETTY_PRINT_2DA

//Multiclass CLAB

COPY_EXISTING ~RAMask.2da~ ~override/RAMaskCT.2da~
SET_2DA_ENTRY 9 25 50 ~AP_RATMASK~
PRETTY_PRINT_2DA

PRETTY_PRINT_2DA

//Restriction

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 98 99 104 105 106 BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAMask + 0x4000)
			  parameter2 = 9
			  timing = 2
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "3A" "D1" "D2" "D3" "D4" "C0" "C1" "C2" "C3" "C4" "C5" "C6" BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAMask~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

//BAM

ACTION_FOR_EACH file IN ~MASKS~ ~MASKL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~MASKSHAD~ ~MASKDARK~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF