//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					   DUSKY, THE SILENTWALKER OF MASK
//__________________________________________________________________________________
//__________________________________________________________________________________

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS ~9~ "rows"
  FOR ( index = 31 ; index < rows ; index = index + 1 ) BEGIN
    READ_2DA_ENTRY "%index%" 5 9 "clab"
    PATCH_IF ("%clab%" STRING_COMPARE_CASE "RAMaskCT" = 0) BEGIN
      READ_2DA_ENTRY "%index%" 0 9 "RAMaskCT"
      SET "rows" = 0
    END
  END
  BUT_ONLY_IF_IT_CHANGES

OUTER_SET kit = "%RAMaskCT%"

COPY_EXISTING_REGEXP GLOB ~.*dusky.cre$~ ~override~
	  WRITE_SHORT   0x244 0
      WRITE_BYTE    0x246 "%kit%"
      WRITE_BYTE    0x247 0x40
BUT_ONLY

//EoF