//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						      Lorekeeper of Oghma
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAOghm~
    ~RAOghm 0 0 0 0 1 1 0 1~
    ~RAOghm 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAOghm 3 3 3 12 14 3~
	~RAOghm 0 0 0 0 0 0~
	~RAOghm 3 3 3 12 14 3~
    ~RAOghm 3 3 3 12 14 3~
	~RAOghm 0 0 0 0 1 0 0 0 0~
	~RAOghm 0 0 1 0 0 0~
	~DeitiesOfFaerun/Tables/RAOghm.2da~
	~K_C_H   K_C_HE   K_C_E   K_C_G   K_C_HL   K_C_D~
	~0x00000000 3~
	~Cl0~
	~CHAN13 * HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * STAF20 HAMM09 *~
	SAY @1201
	SAY @1202
	SAY @1203

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAOghm~
		clascolr = ~205 254 105 22 202~
		clsrcreq = ~1 1 1 1 1 1 0~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RAOGHM~  clabfile = ~RAOGHM~	END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAHSOGHM.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSOGHM~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RAHSOGHM.itm~ SAY NAME1 @1204 SAY NAME2 @1204 SAY DESC @1205
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAOghm + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~OGHMS~
WRITE_ASCII 0x058 ~OGHML~

//Spells

//Free Action (Feature)

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_FREE_ACTION[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_FREE_ACTION~	RET	spell_res	END

COPY_EXISTING ~%spell_res%.spl~	~override/RAOGHMF.spl~
LPM ~SPELL_TO_FEATURE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 parameter1 = ~-1~ target = 2 timing = 9 STR_VAR resource = ~RAOGHMF~ END

END

//Friends

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_FRIENDS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_FRIENDS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAOGHM1.spl~
LPF	CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RAOGHM1~ END
LPM ~SPELL_TO_INNATE~

COPY_EXISTING	~%spell_res%.spl~	override
LPF	CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RAOGHM1~ END

END

//Legend Lore

COPY ~DeitiesOfFaerun/Spl/RAOGHM2.spl~ override SAY NAME1 @1206 SAY UNIDENTIFIED_DESC @1207
LPF ALTER_EFFECT INT_VAR match_parameter2 = 1 match_opcode = 171 STR_VAR resource = EVAL ~RAOGHM21~ END
LPF ALTER_EFFECT INT_VAR match_parameter2 = 2 match_opcode = 171 STR_VAR resource = EVAL ~RAOGHM22~ END
LPF ALTER_EFFECT INT_VAR match_parameter2 = 3 match_opcode = 171 STR_VAR resource = EVAL ~RAOGHM23~ END
LPF ALTER_EFFECT INT_VAR match_parameter2 = 1 match_opcode = 172 STR_VAR resource = EVAL ~RAOGHM21~ END
LPF ALTER_EFFECT INT_VAR match_parameter2 = 2 match_opcode = 172 STR_VAR resource = EVAL ~RAOGHM22~ END
LPF ALTER_EFFECT INT_VAR match_parameter2 = 3 match_opcode = 172 STR_VAR resource = EVAL ~RAOGHM23~ END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_REMOVE_CURSE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_REMOVE_CURSE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAOGHM21.spl~
LPM ~SPELL_TO_INNATE~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_CURE_DISEASE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_CURE_DISEASE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAOGHM22.spl~
LPF	CLONE_EFFECT INT_VAR match_opcode = 324 silent = 1 STR_VAR match_resource = EVAL ~%spell_res%~ resource = EVAL ~RAOGHM22~ END
LPM ~SPELL_TO_INNATE~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_NEUTRALIZE_POISON[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_NEUTRALIZE_POISON~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAOGHM23.spl~
LPM ~SPELL_TO_INNATE~

END


//Multiclass CLAB

COPY_EXISTING ~RAOghm.2da~ ~override/RAOghmCM.2da~
SET_2DA_ENTRY 6 25 50 ~AP_RAMOGHM~
SET_2DA_ENTRY 6  1 50 ~AP_RASLOT~
PRETTY_PRINT_2DA

//BAM

ACTION_FOR_EACH file IN ~OGHMS~ ~OGHML~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~OGHMLELO~ BEGIN
COPY ~DeitiesOfFaerun/Spl/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF