//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						          Seer of Savras
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RASavr~
    ~RASavr 0 0 0 0 1 1 0 1~
    ~RASavr 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RASavr 3 3 3 11 14 3~
	~RASavr 0 0 0 0 0 0~
	~RASavr 3 3 3 11 14 3~
    ~RASavr 3 3 3 11 14 3~
	~RASavr 0 1 0 0 0 0 0 0 0~
	~RASavr 0 0 1 0 0 0~
	~DeitiesOfFaerun\Tables\RASavr.2da~
	~K_C_H K_C_HE K_C_E~
	~0x00000000 3~
	~Cl0~
	~* SHLD22 HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * STAF10 BLUN25 *~
	SAY @3101
	SAY @3102
	SAY @3103

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RASavr~
		clascolr = ~24 146 50 51 81~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 0 0 1 0~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERES.tpa~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RASAVR~  clabfile = ~RASAVR~	END

END

COPY "DeitiesOfFaerun\Spl\RASavrF.spl" override

COPY "DeitiesOfFaerun\Spl\RAHSSAVR.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSSAVR.itm" override SAY NAME1 @3104 SAY NAME2 @3104 SAY DESC @3105
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = IDS_OF_SYMBOL (~Kit~ ~RASavr~)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY "DeitiesOfFaerun\Spl\RAForeIc.bam" override
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(@2908) STR_VAR bam_file = RAFOREIC RET iconfors = icon END
		  
COPY_EXISTING ~SPWI301.spl~ ~override/RASavr1.spl~    											//Clairvoyance
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPWI425.spl~ ~override/RASavr2.spl~    											//Wizard Eye
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPPR505.spl~ ~override/RASavr3.spl~    											//True Seeing
LPM SPELL_TO_INNATE

COPY_EXISTING ~SPPR415.spl~ ~override/RASavr4.spl~    											//Farsight
LPM SPELL_TO_INNATE

COPY "DeitiesOfFaerun\Spl\RASavr5.spl" override SAY NAME1 @2906 SAY UNIDENTIFIED_DESC @2907     //Consequence
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_parameter2 = 1 parameter2 = iconfors END

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RASavr + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@3102)
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "3A" "2A" BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RASavr~) parameter2 = 9 special = RESOLVE_STR_REF (@3102) END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~SAVRS~ ~SAVRL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~SAVRCONS~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF