//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						      Silverstar of Selûne
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RASelu~
    ~RASelu 0 0 0 0 1 1 0 1~
    ~RASelu 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RASelu 3 3 12 3 14 3~
	~RASelu 0 0 0 0 0 0~
	~RASelu 3 3 12 3 14 3~
    ~RASelu 3 3 12 3 14 3~
	~RASelu 0 0 0 0 0 0 1 0 0~
	~RASelu 1 0 1 0 0 0~
	~DeitiesOfFaerun\Tables\RASelu.2da~
	~K_C_H K_C_HO K_C_HE K_C_D K_C_HL K_C_G K_C_E~
	~0x04000000 3~
	~Cl0~
	~PLAT16 * HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * STAF10 HAMM09 *~
	SAY @2001
	SAY @2002
	SAY @2003

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RASelu~
		clascolr = ~79 222 123 97 102~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 1 1 1 1 1 1~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERES.tpa~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RASELU~  clabfile = ~RASELU~	END

END

COPY "DeitiesOfFaerun\Spl\RAHSSELU.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@3) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSSELU.itm" override SAY NAME1 @2010 SAY NAME2 @2010 SAY DESC @2011
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RASelu + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END

COPY ~DeitiesOfFaerun\Spl\RASELUF.spl~ override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL "%RA_Blinded%" END

COPY ~DeitiesOfFaerun\Spl\RASELU1.spl~ override SAY NAME1 @2004 SAY UNIDENTIFIED_DESC @2005
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL "%RA_Blinded%" END

ACTION_IF GAME_IS ~bgee bg2ee eet~ BEGIN

COPY ~DeitiesOfFaerun\Spl\Import\Selune\Complement~ override

COPY ~DeitiesOfFaerun\Spl\Import\Selune\MOONBLA.itm~ override SAY NAME1 @2006 SAY NAME2 @2006 SAY DESC @2006

COPY ~DeitiesOfFaerun\Spl\Import\Selune\RAPR322.spl~ ~override/RASELU2.spl~ SAY NAME1 @2006 SAY UNIDENTIFIED_DESC @2007
LPM SPELL_TO_INNATE

END		  

ACTION_IF GAME_IS ~iwdee~ BEGIN

COPY_EXISTING ~SPPR322.spl~ ~override\RASELU2.spl~
LPM SPELL_TO_INNATE

END

COPY_EXISTING ~SPPR505.spl~ ~override\RASELU3.spl~
LPM SPELL_TO_INNATE
		  
ADD_PROJECTILE ~DeitiesOfFaerun\Spl\RASELU4.PRO~

COPY "DeitiesOfFaerun\Spl\UB!SSta1.bam" override

COPY "DeitiesOfFaerun\Spl\RASELU4.spl" override SAY NAME1 @2008 SAY UNIDENTIFIED_DESC @2009
LPF ALTER_SPELL_HEADER INT_VAR projectile = %RASELU4% END


COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RASelu + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@2002)
		  END
		END
		DEFAULT
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~SELUS~ ~SELUL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~SELUSHST~ ~SELUMOBE~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END	

//EoF