//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        Nightcloak of Shar
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAShar~
    ~RAShar 0 0 0 0 1 1 0 0~
    ~RAShar 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAShar 14 3 3 3 12 3~
	~RAShar 0 0 0 0 0 0~
	~RAShar 14 3 3 3 12 3~
    ~RAShar 14 3 3 3 12 3~
	~RAShar 0 0 0 0 0 1 0 0 0~
	~RAShar 0 0 1 1 0 0~
	~DeitiesOfFaerun/Tables/RAShar.2da~
	~K_C_H   K_C_HE   K_C_E   K_C_G   K_C_HO   K_C_HL   K_C_D~
	~0x00000000 3~
	~Cl0~
	~CHAN18 SHLD20 HELM04 * RING05 RING39 CLCK03 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * BLUN14 WAFLAIL *~
	SAY @401
	SAY @402
	SAY @403

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAShar~
		clascolr = ~247 186 204 41 229~
		clsrcreq = ~1 1 1 1 1 1 1~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RASHAR~  clabfile = ~RASHAR~	END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAHSSHAR.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSSHAR~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RAHSSHAR.itm~ SAY NAME1 @404 SAY NAME2 @404 SAY DESC @405
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAShar + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~SHARS~
WRITE_ASCII 0x058 ~SHARL~

//Spells

COPY ~DeitiesOfFaerun/Spl/RASHARF.spl~ override

COPY ~DeitiesOfFaerun/Spl/RASHARFE.eff~ override

COPY ~DeitiesOfFaerun/Spl/RASHAREF.spl~ override

//Darkness

ACTION_IF !FILE_EXISTS_IN_GAME ~RADARK.PRO~ BEGIN
	ADD_PROJECTILE ~DeitiesOfFaerun/Spl/RADARK.PRO~
	COPY ~DeitiesOfFaerun/Spl/UB!Dark.bam~ override
END ELSE BEGIN
	OUTER_SPRINT	file ~RADARK~
	COPY_EXISTING ~PROJECTL.IDS~	override
		REPLACE_EVALUATE ~[%WNL%^]\(0x[0-9A-F]+\|[0-9]+\)[ %TAB%]+%file%[ %TAB%%WNL%$]~	BEGIN	SET	EVAL ~%file%~ = (~%MATCH1%~ +1)	END	~%MATCH0%~
	BUT_ONLY
END

COPY ~DeitiesOfFaerun/Spl/RASHAR1.spl~ override  SAY NAME1 @406 SAY  UNIDENTIFIED_DESC @407 
LPF ALTER_SPELL_HEADER INT_VAR projectile = %RADARK% END	
LPF ALTER_EFFECT   	   INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Blinded%~ END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_RADUZIEL_LIGHT~ RET spell_res END

COPY_EXISTING ~RASHAR1.spl~ override

LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 resist_dispel = 1 STR_VAR resource = EVAL ~%spell_res%~ insert_point = 0 END

END

//Blindness

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_BLINDNESS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_BLINDNESS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHAR2.spl~
LPM ~SPELL_TO_INNATE~

END

COPY ~DeitiesOfFaerun/Spl/RASHAR3.spl~ override  SAY NAME1 @408 SAY UNIDENTIFIED_DESC @409  //Nightmare


//Shadow Door

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_SHADOW_DOOR[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_SHADOW_DOOR~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHAR4.spl~
LPM ~SPELL_TO_INNATE~

END

COPY ~DeitiesOfFaerun/Spl/RASHAR5.vvc~ override

COPY ~DeitiesOfFaerun/Spl/RASHAR5.spl~ override  SAY NAME1 @410 SAY UNIDENTIFIED_DESC @411  //Eyebite

COPY ~DeitiesOfFaerun/Spl/RASHARE1.spl~ override SAY NAME1 @412 SAY UNIDENTIFIED_DESC @412  //Charm Gaze
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Dominated%~ END
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 2; i < 51; ++i)	BEGIN
		INSERT_BYTES	(ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE	(ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES	(fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE	(fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68	ab_num
	WRITE_LONG	0x6a	fx_off
	FOR (i = 1; i <  51;  ++i)	BEGIN
		LPF	ALTER_EFFECT	INT_VAR	header = (i - 1) match_duration = 6 duration = (6 * ((i + 2)/3))  END
	END
	
COPY ~DeitiesOfFaerun/Spl/RASHARE2.spl~ override SAY NAME1 @413 SAY UNIDENTIFIED_DESC @413  //Fear Gaze
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Panic%~ END
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 2; i < 51; ++i)	BEGIN
		INSERT_BYTES	(ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE	(ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES	(fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE	(fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68	ab_num
	WRITE_LONG	0x6a	fx_off
	FOR (i = 1; i <  51;  ++i)	BEGIN
		LPF	ALTER_EFFECT	INT_VAR	header = (i - 1) match_duration = 6 duration = (6 * ((i + 2)/3))  END
	END

COPY ~DeitiesOfFaerun/Spl/RASHARE3.spl~ override SAY NAME1 @414 SAY UNIDENTIFIED_DESC @414  //Sicken Gaze
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_FoulDisease%~ END
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 2; i < 51; ++i)	BEGIN
		INSERT_BYTES	(ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE	(ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES	(fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE	(fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68	ab_num
	WRITE_LONG	0x6a	fx_off
	FOR (i = 1; i <  51;  ++i)	BEGIN
		LPF	ALTER_EFFECT	INT_VAR	header = (i - 1) match_duration = 6 duration = (6 * ((i + 2)/3))  END
	END

COPY ~DeitiesOfFaerun/Spl/RASHARE4.spl~ override SAY NAME1 @415 SAY UNIDENTIFIED_DESC @415  //Sleep Gaze
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Sleep%~ END
	READ_LONG	0x64	ab_off
	READ_SHORT	0x68	ab_num
	READ_LONG	0x6a	fx_off
	READ_ASCII	ab_off	ability (0x28)
	READ_SHORT	(ab_off + 0x1e) fx_num
	READ_SHORT	(ab_off + 0x20) fx_idx
	READ_ASCII	(fx_off + fx_idx * 0x30) effects (fx_num * 0x30)
	FOR (i = 2; i < 51; ++i)	BEGIN
		INSERT_BYTES	(ab_off + ab_num * 0x28) 0x28	SET	fx_off += 0x28
		WRITE_ASCIIE	(ab_off + ab_num * 0x28) ~%ability%~ (0x28)
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x10)	i
		WRITE_SHORT	(ab_off + ab_num * 0x28 + 0x20)	(fx_idx + fx_num)
		INSERT_BYTES	(fx_off + fx_idx * 0x30) (fx_num * 0x30)
		WRITE_ASCIIE	(fx_off + fx_idx * 0x30) ~%effects%~ (fx_num * 0x30)
		SET	fx_idx += fx_num
		SET	ab_num += 1
	END
	WRITE_SHORT	0x68	ab_num
	WRITE_LONG	0x6a	fx_off
	FOR (i = 1; i <  51;  ++i)	BEGIN
		LPF	ALTER_EFFECT	INT_VAR	header = (i - 1) match_duration = 6 duration = (6 * ((i + 2)/3))  END
	END

COPY ~DeitiesOfFaerun/Tables/RASHAR5.2da~ override

//Multiclass CLAB

ACTION_IF !GAME_IS ~iwdee~ BEGIN

COPY_EXISTING ~RAShar.2da~ ~override/RASharCT.2da~
SET_2DA_ENTRY 7 25 50 ~AP_RATSHAR~
PRETTY_PRINT_2DA

END ELSE BEGIN

COPY_EXISTING ~RAShar.2da~ ~override/RASharCT.2da~
SET_2DA_ENTRY 7 25 50 ~AP_RATSHAR~
SET_2DA_ENTRY 1  7 50 ~AP_#EVADE~
PRETTY_PRINT_2DA

END

COPY_EXISTING ~RAShar.2da~ ~override/RASharCM.2da~
SET_2DA_ENTRY 7 25 50 ~AP_RAMSHAR~
SET_2DA_ENTRY 7  1 50 ~AP_RASLOT~
PRETTY_PRINT_2DA

//Restriction

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAShar + 0x4000)
			  parameter2 = 9
			  timing = 2
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	~%animation%~ WITH
				~4A~ BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAShar~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

//BAM

ACTION_FOR_EACH file IN ~SHARS~ ~SHARL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~SHARDARK~ ~SHAREYEB~ ~SHARNIGH~ ~RASHARE1~ ~RASHARE2~ ~RASHARE3~ ~RASHARE4~ BEGIN
COPY ~DeitiesOfFaerun/Spl/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF