//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						      Woodwife of Shiallia
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAShia~
    ~RAShia 1 1 1 1 1 1 1 1~
    ~RAShia 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAShia 3 3 3 3 11 11~
	~RAShia 0 0 0 0 0 0~
	~RAShia 3 3 3 3 11 11~
    ~RAShia 3 3 3 3 11 11~
	~RAShia 0 0 0 1 0 0 0 0 0~
	~RAShia 0 0 0 0 0 1~
	~DeitiesOfFaerun/Tables/RAShia.2da~
	~K_C_H K_C_HE K_C_E K_C_HL K_C_G~
	~0x00000000 3~
	~Cl0~
	~LEAT19 BLUN23 HELM03 * RING31 RING30 CLCK05 BOOT01 AMUL27 BRAC10 BELT06 * * * * * * * STAF10 SLNG05~
	SAY @4201
	SAY @4202
	SAY @4203

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAShia~
		clascolr = ~3 53 113 137 56~
		clsrcreq = ~1 1 1 0 1 1 0~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RASHIA~  clabfile = ~RASHIA~	END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAHSSHIA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RAHSSHIA~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RAHSSHIA.itm~ SAY NAME1 @4204 SAY NAME2 @4204 SAY DESC @4205
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAShia + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~SHIAS~
WRITE_ASCII 0x058 ~SHIAL~

//Features

COPY ~DeitiesOfFaerun/Spl/RASHIAF.spl~ override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@4206) END

//Lay on Hands

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]PALADIN_LAY_ON_HANDS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~PALADIN_LAY_ON_HANDS~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA1.spl~ SAY UNIDENTIFIED_DESC @4207

END

//Entangle

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_ENTANGLE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_ENTANGLE~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA2.spl~
LPM ~SPELL_TO_INNATE~

END

//Goodberry

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_GOOD_BERRIES[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_GOOD_BERRIES~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA3.spl~
LPM ~SPELL_TO_INNATE~

END

//Animal Summoning I

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_ANIMAL_SUMMONING_1[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_ANIMAL_SUMMONING_1~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA4.spl~
LPM ~SPELL_TO_INNATE~

END

//Animal Summoning II

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_ANIMAL_SUMMONING_2[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_ANIMAL_SUMMONING_2~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA5.spl~
LPM ~SPELL_TO_INNATE~

END

//Animal Summoning III

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_ANIMAL_SUMMONING_3[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_ANIMAL_SUMMONING_3~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA6.spl~
LPM ~SPELL_TO_INNATE~

END

//Heal

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_HEAL[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_HEAL~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RASHIA7.spl~
LPM ~SPELL_TO_INNATE~

END

//Multiclass CLAB

ACTION_IF !GAME_IS ~iwdee~ BEGIN

COPY_EXISTING ~RAShia.2da~ ~override/RAShiaRC.2da~
SET_2DA_ENTRY 11 25 50 ~AP_RARSHIA~
PRETTY_PRINT_2DA

END ELSE BEGIN

COPY_EXISTING ~RAShia.2da~ ~override/RAShiaRC.2da~
SET_2DA_ENTRY 11 25 50 ~AP_RARSHIA~
SET_2DA_ENTRY  7  1 50 ~GA_SPCL922~
PRETTY_PRINT_2DA

END

//Restrictions

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 97 98 99 100 101 103 104 105  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAShia + 0x4000)
			  parameter2 = 9
			  timing = 2
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	~%animation%~ WITH
				~4A~ ~3A~ ~D4~ ~D3~ ~C6~ ~C3~ ~C2~ ~C1~  BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAShia~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

//BAM

ACTION_FOR_EACH file IN ~SHIAS~ ~SHIAL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ override
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF