//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						   YVETTE, THE HEARTWARDER OF SUNE
//__________________________________________________________________________________
//__________________________________________________________________________________

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS ~9~ "rows"
  FOR ( index = 31 ; index < rows ; index = index + 1 ) BEGIN
    READ_2DA_ENTRY "%index%" 5 9 "clab"
    PATCH_IF ("%clab%" STRING_COMPARE_CASE "RASune" = 0) BEGIN
      READ_2DA_ENTRY "%index%" 0 9 "RASune"
    END
  END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~yxyve1.cre~ ~override~
 WRITE_BYTE    0x23e 16
 READ_BYTE 	  0x273 class
 PATCH_IF (class = 3) BEGIN
  WRITE_SHORT   0x244 0
  WRITE_BYTE    0x246 RASune
  WRITE_BYTE    0x247 0x40
 END
BUT_ONLY

//EoF