//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						       Holy Champion of Torm
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RATorm~
    ~RATorm 0 0 0 0 1 1 0 1~
    ~RATorm 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RATorm 3 3 12 3 15 3~
	~RATorm 0 0 0 0 0 0~
	~RATorm 3 3 12 3 15 3~
    ~RATorm 3 3 12 3 15 3~
	~RATorm 1 0 0 0 0 0 0 0 0~
	~RATorm 1 0 0 0 0 0~
	~DeitiesOfFaerun\Tables\RATorm.2da~
	~K_C_H K_C_HE K_C_D K_C_HO~
	~0x00000000 3~
	~Cl0~
	~PLAT18 SHLD21 HELM21 * RING09 RING31 CLCK05 BOOT04 AMUL27 BRAC10 BELT04 * * * * * * BLUN14 HAMM09 *~
	SAY @1501
	SAY @1502
	SAY @1503

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RATorm~
		clascolr = ~66 140 190 164 186~
		clswpbon = ~1 0 3~
		clsrcreq = ~1 0 1 1 0 0 1~
		hpclass = ~HPWAR~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RATORM~  clabfile = ~RATORM~	END

END

COPY "DeitiesOfFaerun\Spl\RAHSTORM.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSTORM.itm" override SAY NAME1 @1504 SAY NAME2 @1504 SAY DESC @1505
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = IDS_OF_SYMBOL (~Kit~ ~RATorm~)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  
END


COPY_EXISTING ~SPPR102.spl~ ~override/RATORM1.spl~  //Command
LPM ~SPELL_TO_INNATE~

COPY_EXISTING ~SPPR512.spl~ ~override/RATORM2.spl~  //Greater Command
LPM ~SPELL_TO_INNATE~

COPY_EXISTING ~SPPR612.spl~ ~override/RATORM3.spl~  //Bolt of Glory
LPM ~SPELL_TO_INNATE~

COPY_EXISTING ~SPWI715.spl~ ~override/RATORM4.spl~  //Power Word, Stun
LPM ~SPELL_TO_INNATE~

COPY_EXISTING ~SPPR710.spl~ ~override/RATORM5.spl~  //Holy Word
LPM ~SPELL_TO_INNATE~

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RATorm + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@1502)
		  END
		END
		DEFAULT
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~TORMS~ ~TORML~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF