//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						       Luckbringer of Tymora
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RATymo~
    ~RATymo 0 0 0 0 1 1 0 1~
    ~RATymo 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RATymo 3 14 3 3 15 3~
	~RATymo 0 0 0 0 0 0~
	~RATymo 3 14 3 3 15 3~
    ~RATymo 3 14 3 3 15 3~
	~RATymo 0 0 0 0 0 0 1 0 0~
	~RATymo 0 0 0 1 0 0~
	~DeitiesOfFaerun\Tables\RATymo.2da~
	~K_C_H   K_C_HE   K_C_HL~
	~0x00000000 3~
	~Cl0~
	~PLAT16 SHLD22 HELM04 * RING31 RING09 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * BLUN14 HAMM09 *~
	SAY @3401
	SAY @3402
	SAY @3403

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RATymo~
		clascolr = ~14 96 97 5 17~
		clswpbon = ~0 0 3~
		clsrcreq = ~1 0 1 0 1 0 0~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERES.tpa~ BEGIN

	LAF	BUILD_SPHERE_ACCESS	STR_VAR	kitname = ~RATYMO~  clabfile = ~RATYMO~	END

END

COPY "DeitiesOfFaerun\Spl\RAHSTYMO.spl" override
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@3) END

COPY "DeitiesOfFaerun\Itm\HolySymbols\RAHSTYMO.itm" override SAY NAME1 @3412 SAY NAME2 @3412 SAY DESC @3413
LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RATymo + 0x4000)
			  parameter2 = 9
			  timing = 2
			  power = 1
		  END


COPY_EXISTING ~SPWI209.spl~ ~override/RATymo1.spl~                                                           //Luck
LPM SPELL_TO_INNATE		  

COPY "DeitiesOfFaerun\Spl\RATymo2.spl"  override SAY NAME1 @3404 SAY UNIDENTIFIED_DESC @3405	             //Moment

COPY "DeitiesOfFaerun\Spl\RATymo3.spl"  override SAY NAME1 @3406 SAY UNIDENTIFIED_DESC @3407	             //Favor of Tymora

COPY_EXISTING ~SPWI514.spl~ ~override/RATymo4.spl~                                                           //Lower Resistance
LPM SPELL_TO_INNATE

COPY "DeitiesOfFaerun\Spl\RATymo5.spl"  override SAY NAME1 @3408 SAY UNIDENTIFIED_DESC @3409	             //Luckbolt

COPY "DeitiesOfFaerun\Spl\RATymo51.spl"  override

COPY "DeitiesOfFaerun\Spl\RATymo52.spl"  override

COPY "DeitiesOfFaerun\Spl\RATymo53.spl"  override

COPY "DeitiesOfFaerun\Spl\RATymo6.spl"  override SAY NAME1 @3410 SAY UNIDENTIFIED_DESC @3411	             //Luckbolt

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	PATCH_MATCH proficiency WITH 
		89 90 91 92 93 94 95 96 98 99 103 104 105 106  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RATymo + 0x4000)
			  parameter2 = 9
			  timing = 2
			  special = RESOLVE_STR_REF (@3402)
		  END
		END
		DEFAULT
	END
BUT_ONLY

ACTION_FOR_EACH file IN ~TYMOS~ ~TYMOL~ BEGIN
  COPY ~DeitiesOfFaerun/Itm/HolySymbols/BAM/%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Itm/HolySymbols/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

ACTION_FOR_EACH file IN ~TYMOBLES~ ~TYMOFAVO~ ~TYMOLUCK~ ~TYMOMOME~ BEGIN
COPY ~DeitiesOfFaerun\Spl\BAM\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~DeitiesOfFaerun/Spl/BAM/MOS%original_base_index%.pvrz~
    END
  END
END

//EoF