//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						Fastpaw of Baervan - Ranger/Cleric
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RABaerRC~
    ~RABaerRC 0 1 1 1 1 0 1 1~
    ~RABaerRC 0 1 1 1 1 0 1 1 0 0 0 2 0 0 0 2 0 2 2 0 0 0 0 2 0 2 0 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RABaerRC 3 3 10 3 9 3~
	~RABaerRC 0 0 0 0 0 0~
	~RABaerRC 3 3 10 3 9 3~
    ~RABaerRC 3 3 10 3 9 3~
	~RABaerRC 0 0 0 1 0 0 1 0 0~
	~RABaerRC 0 0 0 0 0 0~
	~override/RABaerRC.2da~
	~K_CR_G~
	~0x00000000 18~
	~CR0~
	~LEAT19 * HELM16 * RING29 RING31 CLCK27 BOOT04 AMUL27 BRAC10 BELT03 * * * * * * BLUN24 WASLING *~
	SAY @701
	SAY @702
	SAY @710

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RABaerRC~
		clascolr = ~251 43 8 91 9~
		clsrcreq = ~0 0 0 0 0 1 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RABaerRC~
      kit_clab = ~RABaerRC~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RABaerRC%	classID = 18 STR_VAR	kitname = ~RABAER~ kitname2 = ~RABAER~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RARBAER.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RARCBAER~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RARCBAER.itm~ SAY NAME1 @704 SAY NAME2 @704 SAY DESC @705
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RABaerRC + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~BAERS~
WRITE_ASCII 0x058 ~BAERL~

//EoF