//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					  Woodwife of Shiallia - Ranger/Cleric
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAShiaRC~
    ~RAShiaRC 1 1 1 1 1 1 1 1~
    ~RAShiaRC 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 2 0 2 0 0 0 0 2 0 0 0 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAShiaRC 3 3 3 3 11 11~
	~RAShiaRC 0 0 0 0 0 0~
	~RAShiaRC 3 3 3 3 11 11~
    ~RAShiaRC 3 3 3 3 11 11~
	~RAShiaRC 0 0 0 1 0 0 0 0 0~
	~RAShiaRC 0 0 0 0 0 0~
	~override/RAShiaRC.2da~
	~K_CR_H K_CR_HE K_CR_E K_CR_HL K_CR_G~
	~0x00000000 18~
	~CR0~
	~LEAT19 BLUN23 HELM03 * RING31 RING30 CLCK05 BOOT01 AMUL27 BRAC10 BELT06 * * * * * * * STAF10 SLNG05~
	SAY @4201
	SAY @4202
	SAY @4208

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAShiaRC~
		clascolr = ~3 53 113 137 56~
		clsrcreq = ~1 1 1 0 1 1 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAShiaRC~
      kit_clab = ~RAShiaRC~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAShiaRC%	classID = 18 STR_VAR	kitname = ~RASHIA~ kitname2 = ~RASHIA~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RARSHIA.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RARCSHIA~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RARCSHIA.itm~ SAY NAME1 @4204 SAY NAME2 @4204 SAY DESC @4205
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAShiaRC + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~SHIAS~
WRITE_ASCII 0x058 ~SHIAL~

//EoF