//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						Waveservant of Umberlee - Cleric/Thief
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAUmbeCT~
    ~RAUmbeCT 0 1 0 1 1 1 0 1~
    ~RAUmbeCT 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAUmbeCT 3 3 15 3 13 3~
	~RAUmbeCT 0 0 0 0 0 0~
	~RAUmbeCT 3 3 15 3 13 3~
    ~RAUmbeCT 3 3 15 3 13 3~
	~RAUmbeCT 0 0 0 0 0 0 0 0 1~
	~RAUmbeCT 0 0 0 0 0 0~
	~override/RAUmbeCT.2da~
	~K_CT_H K_CT_HO K_CT_HE~
	~0x00000000 15~
	~CT0~
	~LEAT19 * HELM07 * RING07 RING33 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * WASPEAR HAMM09 *~
	SAY @1901
	SAY @1902
	SAY @1910

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAUmbeCT~
		clascolr = ~81 55 125 15 15~
		clsrcreq = ~1 0 1 0 0 0 1~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAUmbeCT~
      kit_clab = ~RAUmbeCT~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAUmbeCT%	classID = 15 STR_VAR	kitname = ~RAUMBE~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RATUMBE.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACTUMBE~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACTUMBE.itm~ SAY NAME1 @1904 SAY NAME2 @1904 SAY DESC @1905
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAUmbeCT + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~UMBES~
WRITE_ASCII 0x058 ~UMBEL~

//EoF