//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						Necrophant of Velsharoon - Cleric/Mage
//__________________________________________________________________________________
//__________________________________________________________________________________

ADD_KIT ~RAVelsCM~
    ~RAVelsCM 0 0 0 0 1 1 0 1~
    ~RAVelsCM 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAVelsCM 3 3 3 11 16 3~
	~RAVelsCM 0 0 0 0 0 0~
	~RAVelsCM 3 3 3 11 16 3~
    ~RAVelsCM 3 3 3 11 16 3~
	~RAVelsCM 0 0 1 0 0 1 0 0 1~
	~RAVelsCM 0 0 0 0 0 0~
	~override/RAVelsCM.2da~
	~K_CM_H~
	~0x00001000 14~
	~CM0~
	~WA2ROBE SHLD22 HELM07 * RING07 RING39 CLCK05 BOOT04 AMUL27 BRAC10 BELT06 * * * * * * STAF11 BLUN25 *~
	SAY @3201
	SAY @3202
	SAY @3209

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAVelsCM~
		clascolr = ~67 99 16 137 17~
		clsrcreq = ~1 0 0 0 0 0 0~
END

LAF qd_multiclass
  STR_VAR 
      kit_name = ~RAVelsCM~
      kit_clab = ~RAVelsCM~
      base_class = ~P~
END

//Sphere

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

LAF	BUILD_SPHERE_ACCESS	INT_VAR	kitid = %RAVelsCM%	classID = 14 STR_VAR	kitname = ~RAVELS~  END

END

//Holy Symbol

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.spl~ ~override/RAMVELS.spl~
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@9999903) END
LPF ALTER_EFFECT INT_VAR match_opcode = 122   STR_VAR resource = ~RACMVELS~ END

COPY ~DeitiesOfFaerun/Itm/HolySymbols/RAHS.itm~ ~override/RACMVELS.itm~ SAY NAME1 @3204 SAY NAME2 @3204 SAY DESC @3205
LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = (RAVelsCM + 0x4000) parameter2 = 9 timing = 2 power = 1 END
WRITE_ASCII 0x03a ~VELSS~
WRITE_ASCII 0x058 ~VELSL~

//EoF