//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						   CASSIA, THE WATCHER OF HELM
//__________________________________________________________________________________
//__________________________________________________________________________________

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS ~9~ "rows"
  FOR ( index = 31 ; index < rows ; index = index + 1 ) BEGIN
    READ_2DA_ENTRY "%index%" 5 9 "clab"
    PATCH_IF ("%clab%" STRING_COMPARE_CASE "RAHelm" = 0) BEGIN
      READ_2DA_ENTRY "%index%" 0 9 "RAHelm"
      SET "rows" = 0
    END
  END
  BUT_ONLY_IF_IT_CHANGES

OUTER_SET kit = "%RAHelm%"

ACTION_FOR_EACH creature IN ~AWCass~ BEGIN
  
  ACTION_IF FILE_EXISTS_IN_GAME ~%creature%.cre~ THEN BEGIN
	  
	COPY_EXISTING ~%creature%.cre~ ~override~
	  WRITE_SHORT   0x244 0
      WRITE_BYTE    0x246 "%kit%"
      WRITE_BYTE    0x247 0x40
	  REMOVE_CRE_ITEM ~CHAN01~
	  ADD_CRE_ITEM ~PLAT01~ #0 #0 #0 ~NONE~ ~ARMOR~ EQUIP
	  BUT_ONLY
  END 
  
    ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF	UPDATE_NPC_SPHERE INT_VAR kitid = RAHelm STR_VAR npc_file = EVAL ~%creature%~ kitname = ~RAHELM~ kitname2 = ~~ END

  END
  
  END
  
//EoF