//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						        NPC SPELLBOOK
//__________________________________________________________________________________
//__________________________________________________________________________________

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN
	  
	ACTION_FOR_EACH creature IN dorn dorn2 dorn4 dorn6 dorn7 dorn8 dorn9 dorn10 dorn12 dorn14 BEGIN

	LAF	UPDATE_NPC_SPHERE	STR_VAR	npc_file = EVAL ~%creature%~	kitname = ~BLACKGUARD~	kitname2 = ~~	END

END

END

//EoF